### PR TITLE
Venue

### PR DESCRIPTION
**Pull request by RPrudden**
Style venue page.

### CODE REVIEW

**Comment by RPrudden** [comment]
screen shot 2016-04-06 at 14 39 10

**Comment by jacobtomlinson** [comment]
The background looks a little stretched. I think my advice of `900px` was a little much.

**Comment by RPrudden** [comment]
It's actually at 700px! I'll turn it down a bit more.

**Comment by jacobtomlinson** [comment]
Either that or make it wider. Can you set the width to auto?

**Comment by RPrudden** [comment]
screen shot 2016-04-06 at 14 57 30

**Pull request merged**
